name: Bug Report
description: Tell us about unexpected behavior.
title: "[Bug]: "
labels: [bug]
body:
  - type: input
    id: version
    attributes:
      label: Software Version
      description: What version are you running? (luaprettydoc --version)
      placeholder: 0.1.0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What Happened?
      description:
        Describe the Bug to help with our understanding of the issue. This should be specific and clear to help with understanding what happened.
      placeholder: A bug happened!
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What was Expected?
      description:
        Describe what should happen. This should be specific and clear to help with understanding of what is expected.
      placeholder: The bug shouldn't happen!
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Please provide some step-by-step instructions as to how this happened.
    validations:
      required: true
